// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Papu.Entities;

namespace Papu.Migrations
{
    [DbContext(typeof(PapuDbContext))]
    [Migration("20220209171802_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Papu.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Papu.Entities.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FridayId")
                        .HasColumnType("int");

                    b.Property<string>("MethodOfPeparation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MondayId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int?>("SaturdayId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SundayId")
                        .HasColumnType("int");

                    b.Property<int?>("ThursdayId")
                        .HasColumnType("int");

                    b.Property<int?>("TuesdayId")
                        .HasColumnType("int");

                    b.Property<int?>("WednesdayId")
                        .HasColumnType("int");

                    b.HasKey("DishId");

                    b.HasIndex("FridayId");

                    b.HasIndex("MondayId");

                    b.HasIndex("SaturdayId");

                    b.HasIndex("SundayId");

                    b.HasIndex("ThursdayId");

                    b.HasIndex("TuesdayId");

                    b.HasIndex("WednesdayId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("Papu.Entities.Friday", b =>
                {
                    b.Property<int>("FridayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("FridayId");

                    b.ToTable("Fridays");
                });

            modelBuilder.Entity("Papu.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("ProductId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Papu.Entities.KindOf", b =>
                {
                    b.Property<int>("KindOfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KindOfId");

                    b.HasIndex("DishId");

                    b.ToTable("KindsOf");
                });

            modelBuilder.Entity("Papu.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FridayId")
                        .HasColumnType("int");

                    b.Property<int?>("MondayId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SaturdayId")
                        .HasColumnType("int");

                    b.Property<int?>("SundayId")
                        .HasColumnType("int");

                    b.Property<int?>("ThursdayId")
                        .HasColumnType("int");

                    b.Property<int?>("TuesdayId")
                        .HasColumnType("int");

                    b.Property<int?>("WednesdayId")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.HasIndex("FridayId");

                    b.HasIndex("MondayId");

                    b.HasIndex("SaturdayId");

                    b.HasIndex("SundayId");

                    b.HasIndex("ThursdayId");

                    b.HasIndex("TuesdayId");

                    b.HasIndex("WednesdayId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Papu.Entities.Monday", b =>
                {
                    b.Property<int>("MondayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MondayId");

                    b.ToTable("Mondays");
                });

            modelBuilder.Entity("Papu.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DishId")
                        .HasColumnType("int");

                    b.Property<int?>("FridayId")
                        .HasColumnType("int");

                    b.Property<int?>("MondayId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SaturdayId")
                        .HasColumnType("int");

                    b.Property<int?>("SundayId")
                        .HasColumnType("int");

                    b.Property<int?>("ThursdayId")
                        .HasColumnType("int");

                    b.Property<int?>("TuesdayId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int?>("WednesdayId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.HasIndex("DishId");

                    b.HasIndex("FridayId");

                    b.HasIndex("MondayId");

                    b.HasIndex("SaturdayId");

                    b.HasIndex("SundayId");

                    b.HasIndex("ThursdayId");

                    b.HasIndex("TuesdayId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.HasIndex("WednesdayId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Papu.Entities.Saturday", b =>
                {
                    b.Property<int>("SaturdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SaturdayId");

                    b.ToTable("Saturdays");
                });

            modelBuilder.Entity("Papu.Entities.Sunday", b =>
                {
                    b.Property<int>("SundayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SundayId");

                    b.ToTable("Sundays");
                });

            modelBuilder.Entity("Papu.Entities.Thursday", b =>
                {
                    b.Property<int>("ThursdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ThursdayId");

                    b.ToTable("Thursdays");
                });

            modelBuilder.Entity("Papu.Entities.Tuesday", b =>
                {
                    b.Property<int>("TuesdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("TuesdayId");

                    b.ToTable("Tuesdays");
                });

            modelBuilder.Entity("Papu.Entities.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.HasIndex("DishId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Papu.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Papu.Entities.Wednesday", b =>
                {
                    b.Property<int>("WednesdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("WednesdayId");

                    b.ToTable("Wednesdays");
                });

            modelBuilder.Entity("Papu.Entities.Dish", b =>
                {
                    b.HasOne("Papu.Entities.Friday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("FridayId");

                    b.HasOne("Papu.Entities.Monday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("MondayId");

                    b.HasOne("Papu.Entities.Saturday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("SaturdayId");

                    b.HasOne("Papu.Entities.Sunday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("SundayId");

                    b.HasOne("Papu.Entities.Thursday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("ThursdayId");

                    b.HasOne("Papu.Entities.Tuesday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("TuesdayId");

                    b.HasOne("Papu.Entities.Wednesday", null)
                        .WithMany("Dishes")
                        .HasForeignKey("WednesdayId");
                });

            modelBuilder.Entity("Papu.Entities.Group", b =>
                {
                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("Groups")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.KindOf", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("KindsOf")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Papu.Entities.Menu", b =>
                {
                    b.HasOne("Papu.Entities.Friday", "Friday")
                        .WithMany()
                        .HasForeignKey("FridayId");

                    b.HasOne("Papu.Entities.Monday", "Monday")
                        .WithMany()
                        .HasForeignKey("MondayId");

                    b.HasOne("Papu.Entities.Saturday", "Saturday")
                        .WithMany()
                        .HasForeignKey("SaturdayId");

                    b.HasOne("Papu.Entities.Sunday", "Sunday")
                        .WithMany()
                        .HasForeignKey("SundayId");

                    b.HasOne("Papu.Entities.Thursday", "Thursday")
                        .WithMany()
                        .HasForeignKey("ThursdayId");

                    b.HasOne("Papu.Entities.Tuesday", "Tuesday")
                        .WithMany()
                        .HasForeignKey("TuesdayId");

                    b.HasOne("Papu.Entities.Wednesday", "Wednesday")
                        .WithMany()
                        .HasForeignKey("WednesdayId");

                    b.Navigation("Friday");

                    b.Navigation("Monday");

                    b.Navigation("Saturday");

                    b.Navigation("Sunday");

                    b.Navigation("Thursday");

                    b.Navigation("Tuesday");

                    b.Navigation("Wednesday");
                });

            modelBuilder.Entity("Papu.Entities.Product", b =>
                {
                    b.HasOne("Papu.Entities.Category", "Category")
                        .WithOne("Product")
                        .HasForeignKey("Papu.Entities.Product", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("Products")
                        .HasForeignKey("DishId");

                    b.HasOne("Papu.Entities.Friday", null)
                        .WithMany("Products")
                        .HasForeignKey("FridayId");

                    b.HasOne("Papu.Entities.Monday", null)
                        .WithMany("Products")
                        .HasForeignKey("MondayId");

                    b.HasOne("Papu.Entities.Saturday", null)
                        .WithMany("Products")
                        .HasForeignKey("SaturdayId");

                    b.HasOne("Papu.Entities.Sunday", null)
                        .WithMany("Products")
                        .HasForeignKey("SundayId");

                    b.HasOne("Papu.Entities.Thursday", null)
                        .WithMany("Products")
                        .HasForeignKey("ThursdayId");

                    b.HasOne("Papu.Entities.Tuesday", null)
                        .WithMany("Products")
                        .HasForeignKey("TuesdayId");

                    b.HasOne("Papu.Entities.Unit", "Unit")
                        .WithOne("Product")
                        .HasForeignKey("Papu.Entities.Product", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Wednesday", null)
                        .WithMany("Products")
                        .HasForeignKey("WednesdayId");

                    b.Navigation("Category");

                    b.Navigation("Dish");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Papu.Entities.Type", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("Types")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Papu.Entities.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.Dish", b =>
                {
                    b.Navigation("KindsOf");

                    b.Navigation("Products");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("Papu.Entities.Friday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Monday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Product", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Papu.Entities.Saturday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Sunday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Thursday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Tuesday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Unit", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.Wednesday", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
