// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Papu.Entities;

namespace Papu.Migrations
{
    [DbContext(typeof(PapuDbContext))]
    [Migration("20220223210544_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Papu.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Papu.Entities.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DishDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DishImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MethodOfPeparation")
                        .IsRequired()
                        .HasMaxLength(1300)
                        .HasColumnType("nvarchar(1300)");

                    b.Property<int>("Portions")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("PreparationTime")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("Papu.Entities.DishFriday", b =>
                {
                    b.Property<int>("FridayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("FridayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishFridays");
                });

            modelBuilder.Entity("Papu.Entities.DishKindOf", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("KindOfId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "KindOfId");

                    b.HasIndex("KindOfId");

                    b.ToTable("DishKindsOf");
                });

            modelBuilder.Entity("Papu.Entities.DishMonday", b =>
                {
                    b.Property<int>("MondayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("MondayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishMondays");
                });

            modelBuilder.Entity("Papu.Entities.DishSaturday", b =>
                {
                    b.Property<int>("SaturdayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("SaturdayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishSaturdays");
                });

            modelBuilder.Entity("Papu.Entities.DishSunday", b =>
                {
                    b.Property<int>("SundayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("SundayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishSundays");
                });

            modelBuilder.Entity("Papu.Entities.DishThursday", b =>
                {
                    b.Property<int>("ThursdayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("ThursdayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishThursdays");
                });

            modelBuilder.Entity("Papu.Entities.DishTuesday", b =>
                {
                    b.Property<int>("TuesdayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("TuesdayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishTuesdays");
                });

            modelBuilder.Entity("Papu.Entities.DishType", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("DishTypes");
                });

            modelBuilder.Entity("Papu.Entities.DishWednesday", b =>
                {
                    b.Property<int>("WednesdayId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("WednesdayId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishWednesdays");
                });

            modelBuilder.Entity("Papu.Entities.Friday", b =>
                {
                    b.Property<int>("FridayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("FridayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Fridays");
                });

            modelBuilder.Entity("Papu.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Papu.Entities.KindOf", b =>
                {
                    b.Property<int>("KindOfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KindOfName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KindOfId");

                    b.ToTable("KindsOf");
                });

            modelBuilder.Entity("Papu.Entities.Menu", b =>
                {
                    b.Property<int?>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Papu.Entities.Monday", b =>
                {
                    b.Property<int>("MondayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("MondayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Mondays");
                });

            modelBuilder.Entity("Papu.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasMaxLength(8)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Papu.Entities.ProductDish", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("DishProducts");
                });

            modelBuilder.Entity("Papu.Entities.ProductFriday", b =>
                {
                    b.Property<int>("FridayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("FridayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFridays");
                });

            modelBuilder.Entity("Papu.Entities.ProductGroup", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("ProductGroups");
                });

            modelBuilder.Entity("Papu.Entities.ProductMonday", b =>
                {
                    b.Property<int>("MondayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("MondayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMondays");
                });

            modelBuilder.Entity("Papu.Entities.ProductSaturday", b =>
                {
                    b.Property<int>("SaturdayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("SaturdayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSaturdays");
                });

            modelBuilder.Entity("Papu.Entities.ProductSunday", b =>
                {
                    b.Property<int>("SundayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("SundayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSundays");
                });

            modelBuilder.Entity("Papu.Entities.ProductThursday", b =>
                {
                    b.Property<int>("ThursdayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ThursdayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductThursdays");
                });

            modelBuilder.Entity("Papu.Entities.ProductTuesday", b =>
                {
                    b.Property<int>("TuesdayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("TuesdayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTuesdays");
                });

            modelBuilder.Entity("Papu.Entities.ProductWednesday", b =>
                {
                    b.Property<int>("WednesdayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("WednesdayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductWednesdays");
                });

            modelBuilder.Entity("Papu.Entities.Saturday", b =>
                {
                    b.Property<int>("SaturdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("SaturdayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Saturdays");
                });

            modelBuilder.Entity("Papu.Entities.Sunday", b =>
                {
                    b.Property<int>("SundayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("SundayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Sundays");
                });

            modelBuilder.Entity("Papu.Entities.Thursday", b =>
                {
                    b.Property<int>("ThursdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("ThursdayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Thursdays");
                });

            modelBuilder.Entity("Papu.Entities.Tuesday", b =>
                {
                    b.Property<int>("TuesdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("TuesdayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Tuesdays");
                });

            modelBuilder.Entity("Papu.Entities.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Papu.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Papu.Entities.Wednesday", b =>
                {
                    b.Property<int>("WednesdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuRef")
                        .HasColumnType("int");

                    b.HasKey("WednesdayId");

                    b.HasIndex("MenuRef")
                        .IsUnique()
                        .HasFilter("[MenuRef] IS NOT NULL");

                    b.ToTable("Wednesdays");
                });

            modelBuilder.Entity("Papu.Entities.DishFriday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("FridayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Friday", "Friday")
                        .WithMany("FridayDishes")
                        .HasForeignKey("FridayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Friday");
                });

            modelBuilder.Entity("Papu.Entities.DishKindOf", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("DishKindsOf")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.KindOf", "KindOf")
                        .WithMany("DishKindsOf")
                        .HasForeignKey("KindOfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("KindOf");
                });

            modelBuilder.Entity("Papu.Entities.DishMonday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("MondayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Monday", "Monday")
                        .WithMany("MondayDishes")
                        .HasForeignKey("MondayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Monday");
                });

            modelBuilder.Entity("Papu.Entities.DishSaturday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("SaturdayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Saturday", "Saturday")
                        .WithMany("SaturdayDishes")
                        .HasForeignKey("SaturdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Saturday");
                });

            modelBuilder.Entity("Papu.Entities.DishSunday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("SundayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Sunday", "Sunday")
                        .WithMany("SundayDishes")
                        .HasForeignKey("SundayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Sunday");
                });

            modelBuilder.Entity("Papu.Entities.DishThursday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("ThursdayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Thursday", "Thursday")
                        .WithMany("ThursdayDishes")
                        .HasForeignKey("ThursdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Thursday");
                });

            modelBuilder.Entity("Papu.Entities.DishTuesday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("TuesdayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Tuesday", "Tuesday")
                        .WithMany("TuesdayDishes")
                        .HasForeignKey("TuesdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Tuesday");
                });

            modelBuilder.Entity("Papu.Entities.DishType", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("DishTypes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Type", "Type")
                        .WithMany("DishTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Papu.Entities.DishWednesday", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("WednesdayDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Wednesday", "Wednesday")
                        .WithMany("WednesdayDishes")
                        .HasForeignKey("WednesdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Wednesday");
                });

            modelBuilder.Entity("Papu.Entities.Friday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Friday")
                        .HasForeignKey("Papu.Entities.Friday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Monday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Monday")
                        .HasForeignKey("Papu.Entities.Monday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Product", b =>
                {
                    b.HasOne("Papu.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papu.Entities.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Papu.Entities.ProductDish", b =>
                {
                    b.HasOne("Papu.Entities.Dish", "Dish")
                        .WithMany("DishProducts")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("DishProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.ProductFriday", b =>
                {
                    b.HasOne("Papu.Entities.Friday", "Friday")
                        .WithMany("FridayProducts")
                        .HasForeignKey("FridayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("FridayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friday");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.ProductGroup", b =>
                {
                    b.HasOne("Papu.Entities.Group", "Group")
                        .WithMany("ProductGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("ProductGroups")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.ProductMonday", b =>
                {
                    b.HasOne("Papu.Entities.Monday", "Monday")
                        .WithMany("MondayProducts")
                        .HasForeignKey("MondayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("MondayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monday");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Papu.Entities.ProductSaturday", b =>
                {
                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("SaturdayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Saturday", "Saturday")
                        .WithMany("SaturdayProducts")
                        .HasForeignKey("SaturdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Saturday");
                });

            modelBuilder.Entity("Papu.Entities.ProductSunday", b =>
                {
                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("SundayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Sunday", "Sunday")
                        .WithMany("SundayProducts")
                        .HasForeignKey("SundayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sunday");
                });

            modelBuilder.Entity("Papu.Entities.ProductThursday", b =>
                {
                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("ThursdayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Thursday", "Thursday")
                        .WithMany("ThursdayProducts")
                        .HasForeignKey("ThursdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Thursday");
                });

            modelBuilder.Entity("Papu.Entities.ProductTuesday", b =>
                {
                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("TuesdayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Tuesday", "Tuesday")
                        .WithMany("TuesdayProducts")
                        .HasForeignKey("TuesdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tuesday");
                });

            modelBuilder.Entity("Papu.Entities.ProductWednesday", b =>
                {
                    b.HasOne("Papu.Entities.Product", "Product")
                        .WithMany("WednesdayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papu.Entities.Wednesday", "Wednesday")
                        .WithMany("WednesdayProducts")
                        .HasForeignKey("WednesdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wednesday");
                });

            modelBuilder.Entity("Papu.Entities.Saturday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Saturday")
                        .HasForeignKey("Papu.Entities.Saturday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Sunday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Sunday")
                        .HasForeignKey("Papu.Entities.Sunday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Thursday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Thursday")
                        .HasForeignKey("Papu.Entities.Thursday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Tuesday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Tuesday")
                        .HasForeignKey("Papu.Entities.Tuesday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Wednesday", b =>
                {
                    b.HasOne("Papu.Entities.Menu", "Menu")
                        .WithOne("Wednesday")
                        .HasForeignKey("Papu.Entities.Wednesday", "MenuRef")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Papu.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Dish", b =>
                {
                    b.Navigation("DishKindsOf");

                    b.Navigation("DishProducts");

                    b.Navigation("DishTypes");

                    b.Navigation("FridayDishes");

                    b.Navigation("MondayDishes");

                    b.Navigation("SaturdayDishes");

                    b.Navigation("SundayDishes");

                    b.Navigation("ThursdayDishes");

                    b.Navigation("TuesdayDishes");

                    b.Navigation("WednesdayDishes");
                });

            modelBuilder.Entity("Papu.Entities.Friday", b =>
                {
                    b.Navigation("FridayDishes");

                    b.Navigation("FridayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Group", b =>
                {
                    b.Navigation("ProductGroups");
                });

            modelBuilder.Entity("Papu.Entities.KindOf", b =>
                {
                    b.Navigation("DishKindsOf");
                });

            modelBuilder.Entity("Papu.Entities.Menu", b =>
                {
                    b.Navigation("Friday");

                    b.Navigation("Monday");

                    b.Navigation("Saturday");

                    b.Navigation("Sunday");

                    b.Navigation("Thursday");

                    b.Navigation("Tuesday");

                    b.Navigation("Wednesday");
                });

            modelBuilder.Entity("Papu.Entities.Monday", b =>
                {
                    b.Navigation("MondayDishes");

                    b.Navigation("MondayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Product", b =>
                {
                    b.Navigation("DishProducts");

                    b.Navigation("FridayProducts");

                    b.Navigation("MondayProducts");

                    b.Navigation("ProductGroups");

                    b.Navigation("SaturdayProducts");

                    b.Navigation("SundayProducts");

                    b.Navigation("ThursdayProducts");

                    b.Navigation("TuesdayProducts");

                    b.Navigation("WednesdayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Saturday", b =>
                {
                    b.Navigation("SaturdayDishes");

                    b.Navigation("SaturdayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Sunday", b =>
                {
                    b.Navigation("SundayDishes");

                    b.Navigation("SundayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Thursday", b =>
                {
                    b.Navigation("ThursdayDishes");

                    b.Navigation("ThursdayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Tuesday", b =>
                {
                    b.Navigation("TuesdayDishes");

                    b.Navigation("TuesdayProducts");
                });

            modelBuilder.Entity("Papu.Entities.Type", b =>
                {
                    b.Navigation("DishTypes");
                });

            modelBuilder.Entity("Papu.Entities.Unit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Papu.Entities.Wednesday", b =>
                {
                    b.Navigation("WednesdayDishes");

                    b.Navigation("WednesdayProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
